### ISSUE TITLE
invalid option: -S

### ISSUE THREAD

**Issue by ramontayag** [candlerb/snailgun#15]
I get this, and I don't know why:

```
$ fautotest
invalid option: -S
/home/ramon/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/optparse.rb:1450:in `complete'
/home/ramon/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/optparse.rb:1448:in `catch'
/home/ramon/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/optparse.rb:1448:in `complete'
/home/ramon/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/optparse.rb:1287:in `parse_in_order'
/home/ramon/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/optparse.rb:1254:in `catch'
/home/ramon/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/optparse.rb:1254:in `parse_in_order'
/home/ramon/.rvm/rubies/ree-1.8.7-2011.03/lib/ruby/1.8/optparse.rb:1248:in `order!'
/home/ramon/.rvm/gems/ree-1.8.7-2011.03@rails3/gems/snailgun-1.1.1/lib/snailgun/server.rb:74:in `start_ruby'
/home/ramon/.rvm/gems/ree-1.8.7-2011.03@rails3/gems/snailgun-1.1.1/lib/snailgun/server.rb:53:in `run'
/home/ramon/.rvm/gems/ree-1.8.7-2011.03@rails3/gems/snailgun-1.1.1/lib/snailgun/server.rb:29:in `fork'
/home/ramon/.rvm/gems/ree-1.8.7-2011.03@rails3/gems/snailgun-1.1.1/lib/snailgun/server.rb:29:in `run'
/home/ramon/.rvm/gems/ree-1.8.7-2011.03@rails3/gems/snailgun-1.1.1/bin/snailgun:105
/home/ramon/.rvm/gems/ree-1.8.7-2011.03@rails3/gems/snailgun-1.1.1/bin/snailgun:80:in `fork'
/home/ramon/.rvm/gems/ree-1.8.7-2011.03@rails3/gems/snailgun-1.1.1/bin/snailgun:80
/home/ramon/.rvm/gems/ree-1.8.7-2011.03@rails3/gems/snailgun-1.1.1/bin/snailgun:79:in `each'
/home/ramon/.rvm/gems/ree-1.8.7-2011.03@rails3/gems/snailgun-1.1.1/bin/snailgun:79
/home/ramon/.rvm/gems/ree-1.8.7-2011.03@rails3/bin/snailgun:19:in `load'
/home/ramon/.rvm/gems/ree-1.8.7-2011.03@rails3/bin/snailgun:19
```

**Comment by candlerb** [comment]
Somehow autotest passed a -S option, which snailgun doesn't accept.

fruby only implements a small subset of ruby command line options (see lib/snailgun/server.rb line 74 onwards): -e, -I, -r, -KU

Perhaps this could be added by someone who understands what autotest is doing with this option.

**Comment by szymon-przybyl** [comment]
when I try to run spec tests ("snailgun -I spec" and "frake spec") i also get that invalid option: -S at: 
fruby -S bundle exec rspec ./spec/c...
